-- USERS TABLE
CREATE TABLE USERS (
    USER_ID INT PRIMARY KEY,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    PHONE VARCHAR(20),
    AGE INT
);

-- BOOKS TABLE
CREATE TABLE BOOKS (
    ISBN VARCHAR(13) PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    AUTHORS VARCHAR(255),
    DESCRIPTION TEXT,
    COVER_URL VARCHAR(500)
);

-- SAVED TABLE
CREATE TABLE SAVED (
    USER_ID INT,
    ISBN VARCHAR(13),
    TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CATEGORY VARCHAR(20) NOT NULL,

    PRIMARY KEY (USER_ID, ISBN),

    FOREIGN KEY (USER_ID) REFERENCES Users(USER_ID),
    FOREIGN KEY (ISBN) REFERENCES Books(ISBN),

    CHECK (CATEGORY IN ('Read_Next', 'History', 'Reading'))
);