<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="dashboard.php">BookTracker</a>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <a class="nav-link active" href="dashboard.php">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="browse.php">Search</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="mybooks.php">My Books</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="account.php">Account</a>
          </li>
        </ul>

        <a href="../api/logout.php" class="btn btn-outline-light">Logout</a>
      </div>
    </div>
</nav>